steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/jobs-web:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/jobs-web:latest'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=${_API_URL}'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/jobs-web:$SHORT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/jobs-web:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'jobs-web'
      - '--image'
      - 'gcr.io/$PROJECT_ID/jobs-web:$SHORT_SHA'
      - '--region'
      - 'australia-southeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'NEXT_PUBLIC_API_URL=${_API_URL}'

substitutions:
  _API_URL: 'https://jobs-api-e3b7ctuuxa-ts.a.run.app'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

images:
  - 'gcr.io/$PROJECT_ID/jobs-web:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/jobs-web:latest'
